---
name: configure_mac_move_detection
pack: network_essentials
runner_type: run-python
description: This configures the switch to enable MAC move detection and set the threshold
  for the number of MAC moves in time-window to trigger the detection.
enabled: true
entry_point: configure_mac_move_detection.py
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    position: 1
  password:
    type: string
    description: THe login password to connect to the device.
    secret: true
    position: 2
  move_threshold:
    type: integer
    description: The MAC move threshold <NUMBER:5-500>.
    default: 5
    required: true
    position: 3
