---
name: configure_logical_interface
pack: network_essentials
runner_type: python-script
description: Create logical interface under the physical/port-channel interface and
  untag/tag vlan.
enabled: true
entry_point: configure_logical_interface.py
parameters:
  mgmt_ip:
    type: string
    description: Management IP address of the target device
    required: true
    position: 0
  username:
    type: string
    description: Login user name to connect to the device
    position: 1
  password:
    type: string
    description: Login password to connect to the device
    secret: true
    position: 2
  intf_type:
    type: string
    enum:
      - ethernet
      - port_channel
    default: ethernet
    description: Interface type
    position: 3
  intf_name:
    type: string
    description: Interface Port number or Port channel number. Examples for SLX are
      1/13, 1/14
    required: true
    position: 4
  logical_interface_number:
    type: string 
    description: Interface name physical port or port channel number. E.g:0/1.1 or
      7.1
    required: true
    position: 5
  vlan_type:
    type: string
    enum:
      - untagged
      - tagged
      - double_tagged
    description: vlan tag type
    position: 6
  vlan_id:
    type: string
    description: Single/List of VLANIDs. Vlan id range <1-4090>
    position: 7
  inner_vlan_id:
    type: string
    description: Configure Single/List of Inner VLAN for the logical interface.vlan
      id range <1-4090>
    position: 8
