---
name: configure_mac_move_detection
pack: network_essentials
runner_type: run-python
description: Configure the switch to enable MAC move detection and set the threshold for number of MAC moves in time-window to trigger the detection.
enabled: true
entry_point: configure_mac_move_detection.py
parameters:
  mgmt_ip:
    type: string
    description: Management IP address of the target device
    required: true
    position: 0
  username:
    type: string
    description: Login user name to connect to the device
    default: admin
    position: 1
  password:
    type: string
    description: Login password to connect to the device
    default: password
    secret: true
    position: 2
  move_threshold:
    type: integer
    description: MAC move threshold <NUMBER:5-500>
    default: 5
    required: true
    position: 3
