---
name: configure_mac_group
pack: network_essentials
runner_type: python-script
description: This creates a new MAC group on a device and configures the member MAC addresses.
enabled: true
entry_point: configure_mac_group.py
parameters:
  mgmt_ip:
    type: string
    description: The management IP address of the target device.
    required: true
    position: 0
  username:
    type: string
    description: The login user name to connect to the device.
    position: 1
  password:
    type: string
    description: The login password to connect to the device.
    secret: true
    position: 2
  mac_group_id:
    type: integer
    description: The MAC group ID <NUMBER:1,500>.
    required: true
    position: 3
  mac_address:
    type: array
    description: A single or comma seperated list of MAC addresses to be part of the
      MAC group. The MAC address is in HHHH.HHHH.HHHH format.
    position: 4
