---
name: configure_conversational_arp_evpn
pack: network_essentials
runner_type: run-python
description: configure conversational arp on VDX switches
enabled: true
entry_point: configure_conversational_arp_evpn.py
parameters:
  mgmt_ip:
    type: string
    description: Device to get the NOS version
    required: true
    position: 0
  username:
    type: string
    description: login username
    default: admin
    position: 1
  password:
    type: string
    description: login password
    default: password
    secret: true
    position: 2
