---
name: configure_anycast_gw_mac_evpn
runner_type: run-python
description: Affect an anycast gateway change on VDX switches
enabled: true
entry_point: configure_anycast.py
parameters:
  mgmt_ip:
    type: string
    description: Management IP of the Device
    required: true
    position: 0
  username:
    type: string
    description: login username
    default: admin
    position: 1
  password:
    type: string
    description: login password
    default: password
    secret: true
    position: 2
  rbridge_id:
    type: string
    description: rbridge id under which anycast MAC will be configured
    required: true
    position: 3
  mac:
    type: string
    description: Anycast MAC to configure
    required: true
    position: 4
