---
name: configure_mgmt_virtual_ip
pack: network_essentials
runner_type: run-python
description: Configure Management virtual IP on a device
enabled: true
entry_point: configure_mgmt_virtual_ip.py
parameters:
  principal_mgmt_ip:
    type: string
    description: Management IP of the principal rbridge.
    required: true
    position: 0
  username:
    type: string
    description: login username
    default: admin
    position: 2
  password:
    type: string
    description: login password
    default: password
    secret: true
    position: 3
  mgmt_vip:
    type: string
    description: Management Virtual IPv4/IPv6 of VCS Fabric along with netmask(example 10.1.1.1/22, 2620:100:0:fa48:34::50/64).
    required: true
    position: 1
