---
name: configure_evpn_vtep
pack: network_essentials
runner_type: run-python
description: Configure EVPN VTEP on a leaf/vLAG pair
enabled: true
entry_point: configure_evpn_vtep.py
parameters:
  mgmt_ip:
    type: string
    description: Device to get the NOS version
    required: true
    position: 0
  username:
    type: string
    description: login username
    default: admin
    position: 1
  password:
    type: string
    description: login password
    default: password
    secret: true
    position: 2
  loopback_id:
    type: integer
    description: Loopback id (<NUMBER:1-255>)
    required: true
    position: 3
  rbridge_id:
    type: array
    description: Single/List of rbridge ID's(example rbridge_id=1 or rbridge_id=1,2,3)
    position: 4
  name:
    type: string
    description: Overlay Gateway Name
    required: true
    position: 5
