---
name: configure_vf 
pack: network_essentials 
runner_type: run-python
description: Enable/Disable vcs virtual fabric.
enabled: true
entry_point: configure_vf.py
parameters:
  mgmt_ip:
    type: string
    description: Management IP address of the target device
    required: true
    position: 0
  username:
    type: string
    description: Login user name to connect to the device
    default: admin
    position: 1
  password:
    type: string
    description: Login password to connect to the device
    default: password
    secret: true
    position: 2
  virtual_fabric_enable:
    type: boolean
    description: Enable/Disable VCS Virtual Fabric 
    default: True
    position: 3
