---
name: configure_mac_move_detection
pack: network_essentials
runner_type: run-python
description: configure mac address table mac move detect enable and limit
enabled: true
entry_point: configure_mac_move_detection.py
parameters:
  mgmt_ip:
    type: string
    description: mgmt_ip of the Device
    required: true
    position: 0
  username:
    type: string
    description: login username
    default: admin
    position: 1
  password:
    type: string
    description: login password
    default: password
    secret: true
    position: 2
  move_threshold:
    type: integer
    description: mac move threshold <NUMBER:5-500>
    default: 5
    required: true
    position: 3
